hwdec=auto
#profile=gpu-hq
#gpu-context=wayland
#gpu-hwdec-interop=vaapi
#gpu-context=x11egl

script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-format=bestvideo[ext=mp4]+bestaudio
watch-later-directory=~/.local/state/mpv/watch-later
save-position-on-quit
write-filename-in-watch-later-config

no-keepaspect-window
