hwdec=auto-safe
vo=gpu
profile=gpu-hq
gpu-context=wayland
#gpu-hwdec-interop=vaapi
#gpu-context=x11egl

script-opts=ytdl_hook-ytdl_path=yt-dlp
#vcodec=h264
ytdl-format=bestvideo[vcodec^=avc1]+bestaudio/best[vcodec^=avc1]
#ytdl-format=bestvideo[vcodec!=av01]+bestaudio/best[vcodec!=av01]
watch-later-directory=~/.local/state/mpv/watch-later
save-position-on-quit
write-filename-in-watch-later-config

no-keepaspect-window
