general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting mutliple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on && hyprctl dispatch exec waybar  # to avoid having to press a key twice to turn on the display and ensure waybar is showing
}

listener {
    timeout = 150                               # 2.5 min.
    on-timeout = brightnessctl -s set 10        # set monitor to minimum. Avoid 0 on an OLED monitor.
    on-resume = brightnessctl -r                # monitor backlight resume.
}

listener {
    timeout = 150                               # 2.5 min.
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0  # turn off keyboard backlight
    on-resume = brightnessctl -rd rgb_kbd_backlight         # turn on keyboard backlight`
}

listener {
    timeout = 300                               # 5 min.
    on-timeout = loginctl lock-session          # lock sceen when timeout has passed
}

listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off      # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 1800                              # 30 min
    on-timeout = systemctl suspend              # suspend pc
}
